# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.


# This file was generated by libcst.codegen.gen_matcher_classes
from dataclasses import dataclass
from typing import Literal, Optional, Union

import libcst as cst
from libcst.matchers._base import BaseExpression
from libcst.matchers._match_types import (
    AssignEqualMatchType,
    CommaMatchType,
    MetadataMatchType,
    SimpleWhitespaceMatchType,
    TypeVarOrTypeVarTupleOrParamSpecMatchType,
)
from libcst.matchers._matcher_base import (
    AllOf,
    BaseMatcherNode,
    DoNotCare,
    DoNotCareSentinel,
    MatchIfTrue,
    OneOf,
)


@dataclass(frozen=True, eq=False, unsafe_hash=False)
class TypeParam(BaseMatcherNode):
    param: Union[
        TypeVarOrTypeVarTupleOrParamSpecMatchType,
        DoNotCareSentinel,
        OneOf[TypeVarOrTypeVarTupleOrParamSpecMatchType],
        AllOf[TypeVarOrTypeVarTupleOrParamSpecMatchType],
    ] = DoNotCare()
    comma: Union[
        CommaMatchType, DoNotCareSentinel, OneOf[CommaMatchType], AllOf[CommaMatchType]
    ] = DoNotCare()
    equal: Union[
        AssignEqualMatchType,
        DoNotCareSentinel,
        OneOf[AssignEqualMatchType],
        AllOf[AssignEqualMatchType],
    ] = DoNotCare()
    star: Union[
        Literal["", "*"],
        MetadataMatchType,
        MatchIfTrue[Literal["", "*"]],
        DoNotCareSentinel,
        OneOf[
            Union[Literal["", "*"], MetadataMatchType, MatchIfTrue[Literal["", "*"]]]
        ],
        AllOf[
            Union[Literal["", "*"], MetadataMatchType, MatchIfTrue[Literal["", "*"]]]
        ],
    ] = DoNotCare()
    whitespace_after_star: Union[
        SimpleWhitespaceMatchType,
        DoNotCareSentinel,
        OneOf[SimpleWhitespaceMatchType],
        AllOf[SimpleWhitespaceMatchType],
    ] = DoNotCare()
    default: Union[
        Optional["BaseExpression"],
        MetadataMatchType,
        MatchIfTrue[Optional[cst.BaseExpression]],
        DoNotCareSentinel,
        OneOf[
            Union[
                Optional["BaseExpression"],
                MetadataMatchType,
                MatchIfTrue[Optional[cst.BaseExpression]],
            ]
        ],
        AllOf[
            Union[
                Optional["BaseExpression"],
                MetadataMatchType,
                MatchIfTrue[Optional[cst.BaseExpression]],
            ]
        ],
    ] = DoNotCare()
    metadata: Union[
        MetadataMatchType,
        DoNotCareSentinel,
        OneOf[MetadataMatchType],
        AllOf[MetadataMatchType],
    ] = DoNotCare()
